name: mvvm_sip_demo
description: A VoIP calling app built with MVVM architecture.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  sip_ua: ^1.1.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  logger: ^2.5.0
  collection: ^1.18.0
  crypto: ^3.0.3
  audioplayers: ^6.0.0
  flutter_webrtc: ^1.2.1
  intl: ^0.20.1
  path: ^1.6.4
  random_string: ^2.3.1
  sdp_transform: ^0.3.2
  uuid: ^4.2.1
  get_it: ^9.1.1
  mongo_dart: ^0.10.6
  
  # Merged Dependencies
  http: ^1.6.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.6
  google_fonts: ^6.3.3
  flutter_svg: ^2.2.3
  carousel_slider: ^5.1.1
  badges: ^3.1.2
  cached_network_image: ^3.4.1

  grpc: ^5.0.0
  protobuf: ^5.1.0
  flutter_contacts: ^1.1.9+2
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  import_sorter: ^4.6.0
  test: any
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/
    - assets/icon/
    - assets/images/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
